In [4]:
import pandas as pd
import googlemaps
import numpy as np

API key should be requested from https://console.developers.google.com/. It is not free.

In [5]:
API_key = 'You_API_key'  # enter Google Maps API key
gmaps = googlemaps.Client(key=API_key)

In [6]:
Hospitals=pd.read_csv(r'../data/hospital_resources/Hospital_resources_hanmin.csv', encoding='ISO-8859-1')
total_num=len(Hospitals['ID'])
dist_mat=np.zeros((len(Hospitals['Latitude']),len(Hospitals['Latitude'])))  # distance between hospitals in meters
dura_mat=np.zeros((len(Hospitals['Latitude']),len(Hospitals['Latitude'])))  # duration between hospitals in seconds
Hospitals

ID  KT                                               Inst  \
0     0  BS                         UniversitÌ_tsspital Basel   
1     1  GE    Les H̫pitaux Universitaires de Gen̬ve HUG   
2     2  VD      CHUV Centre Hospitalier Universitaire Vaudois   
3     3  ZH                      UniversitÌ_tsspital ZÌ_rich   
4     4  BE                    Insel Gruppe AG (universitÌ_r)   
..  ...  ..                                                ...   
62  230  GE                                Clinique de Carouge   
63  257  ZH  UniversitÌ_ts-Kinderspital ZÌ_rich das Spita...   
64  258  SG                          Ostschweizer Kinderspital   
65  259  BS    UniversitÌ_ts-Kinderspital beider Basel (UKBB)   
66  273  LU          Schweizer Paraplegiker-Zentrum Nottwil AG   

                                  Adr    PersA    PersP  BettenStatA  \
0                     Hebelstrasse 32   913.50  1595.22   633.000000   
1   Rue Gabrielleå_Perretå_Gentil 4  1829.32  4498.96  1054.282192   
2                    Rue du Bugnon 21  1653.73  3400.37   929.000000   
3                   RÌ_mistrasse 100  1221.75  2574.21   953.884931   
4                  Freiburgstrasse 18  1355.66  2739.25   876.298630   
..                                ...      ...      ...          ...   
62      Avenue Cardinalå_Mermillod 1    14.78    40.46    15.000000   
63                Steinwiesstrasse 75   302.29   683.98   167.128767   
64                  Claudiusstrasse 6    85.25   272.69    74.000000   
65                   Spitalstrasse 33   157.55   411.82   118.501370   
66          Guido A. ZÌ_ch Strasse 1    74.21   364.56    53.000000   

    pBettenBelStatA  ICU_beds  Ventilators   Latitude  Longitude Unnamed: 12  
0         92.463806        38           28  47.561196   7.581541         NaN  
1         85.289218        63           47  46.193711   6.148856         NaN  
2         82.588437        56           41  46.524749   6.639659         NaN  
3         78.680694        57           42  47.376736   8.549199         NaN  
4         83.329008        53           39  46.947455   7.424801         NaN  
..              ...       ...          ...        ...        ...         ...  
62        28.566210         1            1  46.186931   6.142615         NaN  
63        75.649979        10            7  47.372031   8.557767         NaN  
64        81.728989         4            3  47.431105   9.387304         NaN  
65        72.873558         7            5  47.563624   7.581830         NaN  
66        81.540450         3            2  47.141716   8.130885         NaN  

[67 rows x 13 columns]

In [10]:
# Loop through coordinates of hospitals and extract distance according to coordinates via google API. 
for orig_ind in range(0, 66):
    LatOrigin = Hospitals['Latitude'][orig_ind]  
    LongOrigin = Hospitals['Longitude'][orig_ind] 
    origins = (LatOrigin, LongOrigin)  # define origin hospital
    for dest_ind in range(orig_ind+1, 67):
        LatDest = Hospitals['Latitude'][dest_ind] 
        LongDest = Hospitals['Longitude'][dest_ind]  
        destination = (LatDest, LongDest)  # define destination hospital
        print(orig_ind, dest_ind)
        result = gmaps.distance_matrix(origins, destination)
        dist = result['rows'][0]['elements'][0]['distance']['value'] # gives distance in meters
        dura = result['rows'][0]['elements'][0]['duration']['value'] # gives driving duration in seconds
        dist_mat[orig_ind, dest_ind] = dist
        print(dist)
        dura_mat[orig_ind, dest_ind] = dura       
        print(dura)

0 1
255537
10284
0 2
199572
7673
0 3
89225
4298
0 4
101829
4338
0 5
58213
3022
0 6
64097
2724
0 7
58726
2977
0 8
184805
7090
0 9
170980
6803
0 10
204630
7950
0 11
138740
5702
0 12
103327
4454
0 13
71978
3122
0 14
112534
4823
0 15
132638
5380
0 16
19812
1246
0 17
99277
4072
0 18
102414
4490
0 19
238445
9412
0 20
131357
5443
0 21
100464
4731
0 22
204912
7779
0 23
202493
7942
0 24
99726
4147
0 25
101672
4233
0 26
98218
4245
0 27
126608
5667
0 28
95033
4127
0 29
86789
3901
0 30
152963
6189
0 31
86550
3814
0 32
114223
4753
0 33
197491
10417
0 34
103347
4891
0 35
3117
616
0 36
105584
4319
0 37
81666
3507
0 38
89162
3937
0 39
253621
9213
0 40
124398
5089
0 41
169127
6472
0 42
110040
4438
0 43
101753
4193
0 44
64953
3180
0 45
255708
9787
0 46
54377
3881
0 47
138192
5545
0 48
232169
8891
0 49
87001
4076
0 50
94420
4038
0 51
121868
5541
0 52
128088
5041
0 53
264510
10388
0 54
297370
13049
0 55
56942
2634
0 56
145085
5957
0 57
139477
5492
0 58
265732
10466
0 59
112895
4596
0 60
171872
6655
0 61
1

116765
4910
7 62
247770
9556
7 63
49886
2988
7 64
129073
5056
7 65
58758
2996
7 66
32655
2324
8 9
61273
2483
8 10
43938
1953
8 11
259114
9696
8 12
223700
8448
8 13
128274
4802
8 14
232908
8816
8 15
56298
2294
8 16
165853
6197
8 17
195135
7183
8 18
198271
7602
8 19
334303
12523
8 20
251731
9437
8 21
220837
8725
8 22
325286
11773
8 23
322867
11935
8 24
86347
3282
8 25
86119
3251
8 26
89745
3520
8 27
101099
3776
8 28
127370
5070
8 29
112380
4492
8 30
147144
5624
8 31
206924
7807
8 32
234597
8746
8 33
115387
4670
8 34
223720
8884
8 35
180991
6699
8 36
225958
8312
8 37
202040
7501
8 38
209536
7930
8 39
73879
2731
8 40
118579
4524
8 41
289501
10466
8 42
218222
7870
8 43
222127
8186
8 44
140467
5540
8 45
95017
3790
8 46
198790
7987
8 47
234049
8657
8 48
71477
2893
8 49
192345
7525
8 50
214794
8031
8 51
242241
9534
8 52
248462
9035
8 53
360367
13500
8 54
417743
17043
8 55
152799
5746
8 56
66859
3032
8 57
235335
8604
8 58
361590
13578
8 59
208753
7708
8 60
292246
10649
8 61
277270
10344
8 62
10

78478
4638
16 47
120181
4753
16 48
214158
8099
16 49
76870
3555
16 50
84290
3516
16 51
111737
5019
16 52
117957
4519
16 53
246499
9597
16 54
287239
12528
16 55
38931
1843
16 56
127075
5166
16 57
121467
4701
16 58
247722
9674
16 59
94884
3804
16 60
161742
6134
16 61
146766
5829
16 62
247738
9461
16 63
79887
3906
16 64
159073
5975
16 65
19735
1227
16 66
64582
2743
17 18
3947
550
17 19
144272
5991
17 20
105045
4367
17 21
53784
2816
17 22
138418
5571
17 23
162908
6379
17 24
109418
4313
17 25
111364
4398
17 26
107910
4410
17 27
136300
5832
17 28
104725
4292
17 29
96481
4066
17 30
77149
4201
17 31
60239
2737
17 32
87911
3676
17 33
151790
9518
17 34
56667
2976
17 35
94618
3741
17 36
79272
3242
17 37
50878
2173
17 38
51469
2332
17 39
263312
9378
17 40
134090
5254
17 41
142815
5396
17 42
28040
1270
17 43
75441
3116
17 44
52789
2485
17 45
265400
9953
17 46
129518
6038
17 47
43868
2056
17 48
241860
9056
17 49
32414
2015
17 50
47740
2122
17 51
69004
3835
17 52
61594
2833
17 53
170337
6967
17 54
23

203350
7742
26 65
98397
4211
26 66
92223
3898
27 28
31374
1819
27 29
73500
3584
27 30
108264
4716
27 31
149135
6447
27 32
176807
7386
27 33
210580
8125
27 34
165931
7524
27 35
123202
5338
27 36
168169
6952
27 37
144250
6140
27 38
151747
6570
27 39
169072
6186
27 40
79699
3616
27 41
231711
9106
27 42
160432
6510
27 43
164337
6826
27 44
82677
4180
27 45
128208
5079
27 46
84815
4922
27 47
176260
7296
27 48
104668
4182
27 49
134555
6165
27 50
157004
6671
27 51
184452
8174
27 52
190672
7674
27 53
302578
12140
27 54
359954
15683
27 55
95010
4386
27 56
41096
2414
27 57
177545
7244
27 58
303800
12217
27 59
150963
6347
27 60
234457
9289
27 61
219480
8984
27 62
138248
5545
27 63
152601
7062
27 64
231788
9130
27 65
126834
5599
27 66
120660
5286
28 29
49301
2726
28 30
95455
4295
28 31
118965
5194
28 32
146638
6133
28 33
139984
8523
28 34
135761
6271
28 35
93032
4085
28 36
137999
5699
28 37
114080
4887
28 38
121577
5317
28 39
196113
7319
28 40
66891
3195
28 41
201541
7852
28 42
130263
5256
28 43
13

114407
4909
41 50
88454
3902
41 51
102868
4424
41 52
79807
3974
41 53
244223
9707
41 54
193553
8875
41 55
142369
5462
41 56
249708
9452
41 57
168294
6557
41 58
245446
9785
41 59
157745
6068
41 60
4010
413
41 61
122623
4659
41 62
370371
13747
41 63
85791
3730
41 64
76
24
41 65
168691
6443
41 66
158091
6256
42 43
58669
2493
42 44
76673
3268
42 45
289284
10735
42 46
153402
6820
42 47
39054
1852
42 48
265744
9838
42 49
24612
1556
42 50
30968
1499
42 51
45577
2755
42 52
35606
1857
42 53
181610
7511
42 54
204887
9865
42 55
72562
2950
42 56
178661
6905
42 57
54105
2463
42 58
182833
7589
42 59
43557
1973
42 60
128788
4956
42 61
64414
3167
42 62
299324
11200
42 63
34932
2036
42 64
126119
4797
42 65
110253
4436
42 66
43902
2161
43 44
92470
4042
43 45
292976
11003
43 46
157094
7089
43 47
85888
3668
43 48
269436
10107
43 49
47052
2631
43 50
23766
1725
43 51
46827
2584
43 52
61106
3008
43 53
228444
9327
43 54
225614
10950
43 55
75014
3184
43 56
182353
7173
43 57
100939
4279
43 58
229666
9405
43 59


In [15]:
upper_half = dist_mat
lower_half = upper_half.transpose()
dist_mat = np.add(upper_half, lower_half)
print(dist_mat)

[[     0.      0.      0. ...      0.      0.      0.]
 [255537.      0.      0. ...      0.      0.      0.]
 [199572.  70822.      0. ...      0.      0.      0.]
 ...
 [169203. 360327. 304599. ...      0.      0.      0.]
 [   418. 255374. 199645. ... 168767.      0.      0.]
 [ 82592. 249200. 193471. ... 158167.  82168.      0.]]


In [18]:
upper_half = dura_mat
lower_half = upper_half.transpose()
dura_mat = np.add(upper_half, lower_half)
print(dura_mat)

[[    0. 10284.  7673. ...  6497.   125.  3534.]
 [10284.     0.  3369. ... 13660. 10129.  9816.]
 [ 7673.  3369.     0. ... 11102.  7571.  7258.]
 ...
 [ 6497. 13660. 11102. ...     0.  6459.  6272.]
 [  125. 10129.  7571. ...  6459.     0.  3434.]
 [ 3534.  9816.  7258. ...  6272.  3434.     0.]]


In [19]:
np.save(r'../data/hospital_resources/dist_mat', dist_mat)
np.save(r'../data/hospital_resources/dura_mat', dura_mat)